// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzvdipkijnrakicrrynk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dmRpcGtpam5yYWtpY3JyeW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMzA0NjIsImV4cCI6MjA1NTYwNjQ2Mn0.vHWW_wMHCWRqQ9PpA5X_-Q5SULF_BDRDQ5DLddsRtqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);